/**
 * Subject APIs.
 *
 * Code by @trhgquan - https://github.com/trhgquan
 */

#include"Subject.h"

/**
 * This function read a CSV file into vector of Subjects.
 *
 * @param  std::string
 * @return std::vector<Subject>
 */
std::vector<Subject> readSubjectsFromCSVFile(std::string fileName) {
  std::vector<Subject>subjects;

  std::ifstream fileStream(fileName, std::ios::in);
  std::string currentLine;

  int currentLineIndex = 0;

  while (std::getline(fileStream, currentLine)) {
    ++currentLineIndex;

    // Only push lines that have length > 0.
    if (currentLine.length() > 0) {
      // Since there are some bugs on ",," (blank line generated by Excel),
      // this block will ignore it and mentioning it as an input error.
      try {
        Subject subject(currentLine);
        subjects.push_back(subject);
      }
      catch (std::invalid_argument e) {
        std::cout << "Error on line " << currentLineIndex
                  << " of " << fileName
                  << ", error message: " << e.what() << '\n';
      }
    }
  }

  fileStream.close();

  return subjects;
}
